Repository defenseunicorns/lula, pull requests merged in 2024-03, with the labels that each got.

#253 Support for named resources
  docs/kubernetes-domain.md
  docs/opa-provider.md
  src/cmd/validate/validate.go
  src/pkg/common/kubernetes/resource.go
  src/pkg/common/kubernetes/wait.go
  src/test/e2e/pod_validation_test.go
  src/test/e2e/scenarios/pod-label/oscal-component.yaml
  src/test/e2e/scenarios/pod-label/pod.fail.yaml
Labels: enhancement

#310 Feat: enable draft for release process
  .goreleaser.yaml
Labels: enhancement

#309 Fix: Convert mapstructure decode to yaml unmarshall to type
  demo/oscal-component.yaml
  docs/kubernetes-domain.md
  docs/opa-provider.md
  docs/version-specification.md
  go.mod
  go.sum
  src/cmd/validate/validate.go
  src/pkg/common/oscal/component.go
  src/pkg/providers/opa/opa.go
  src/test/e2e/scenarios/multi-resource/oscal-component.yaml
  src/test/e2e/scenarios/outputs/oscal-component.yaml
  src/test/e2e/scenarios/pod-label/oscal-component.yaml
  src/test/e2e/scenarios/resource-data/oscal-component.yaml
  src/test/e2e/scenarios/wait-field/oscal-component.yaml
  src/types/types.go
Labels: bug

#319 feat: add initial mac release
  .github/workflows/release.yaml
  .goreleaser.yaml
Labels: enhancement

#330 Fix: set default CLI_VERSION to unset when no tags are present
  Makefile
Labels: bug

#326 feat: integrate kyverno
  demo/oscal-component-kyverno.yaml
  demo/oscal-component-opa.yaml
  docs/kyverno-provider.md
  go.mod
  go.sum
  src/cmd/validate/validate.go
  src/cmd/version/version.go
  src/pkg/providers/kyverno/kyverno.go
  src/test/e2e/pod_validation_test.go
  src/test/e2e/scenarios/pod-label/oscal-component-kyverno.yaml
  src/types/types.go
Labels: open-source

#331 Docs: Add dependency update guidance to repository
  docs/dependency-updates.md
Labels: documentation

#336 chore: add labels to renovate pull requests
  renovate.json
Labels: dependencies
