Repository defenseunicorns/lula, pull requests merged in 2024-07, with the labels that each got.

#539 fix(test): updated uuid in kyverno validation
  src/test/e2e/scenarios/dev-lint/invalid.opa.validation.yaml
  src/test/e2e/scenarios/dev-lint/multi.validation.yaml
  src/test/e2e/scenarios/dev-lint/opa.validation.yaml
  src/test/e2e/scenarios/dev-lint/validation.kyverno.yaml
  src/test/e2e/scenarios/dev-validate/validation.kyverno.yaml
Labels: bug

#524 chore(docs): initial docs structure/changes for feedback
  README.md
  demo/develop-validation/oscal-component.yaml
  demo/develop-validation/resources-bad.json
  demo/develop-validation/resources.json
  demo/develop-validation/validation.yaml
  demo/simple/namespace.yaml
  demo/simple/oscal-component-kyverno.yaml
  demo/simple/oscal-component-opa.yaml
  demo/simple/pod.fail.yaml
  demo/simple/pod.pass.yaml
  docs/cli-commands/assessments/README.md
  docs/cli-commands/assessments/assess.md
  docs/cli-commands/assessments/evaluate.md
  docs/cli-commands/assessments/validate.md
  docs/cli-commands/dev/README.md
  docs/cli-commands/dev/get_resources.md
  docs/cli-commands/dev/validate.md
  docs/cli-commands/generation/README.md
  docs/cli-commands/generation/component.md
  docs/cli-commands/tools/README.md
  docs/cli-commands/tools/compose.md
  docs/cli-commands/tools/uuidgen.md
  docs/community-and-contribution/README.md
  docs/community-and-contribution/triage-label.md
  docs/getting-started/README.md
  docs/getting-started/develop-a-validation.md
  docs/getting-started/lula-in-ci.md
  docs/getting-started/simple-demo.md
  docs/oscal/README.md
  docs/oscal/assessment-results.md
  docs/reference/domains/README.md
  docs/reference/domains/api-domain.md
  docs/reference/domains/kubernetes-domain.md
  docs/reference/providers/README.md
  lula.svg
  src/cmd/dev/get-resources.go
  src/cmd/dev/validate.go
Labels: documentation

#549 chore(docs): correcting cli command in simple demo
  docs/getting-started/simple-demo.md
Labels: open-source
