Repository defenseunicorns/lula, pull requests merged in 2024-04, with the labels that each got.

#343 Fix: Use Kyverno ValidatingPolicy Structure
  demo/oscal-component-kyverno.yaml
  docs/kyverno-provider.md
  go.mod
  go.sum
  src/pkg/common/oscal/component.go
  src/pkg/providers/kyverno/kyverno.go
  src/test/e2e/scenarios/pod-label/oscal-component-kyverno.yaml
  src/types/types.go
Labels: bug

#363 chore: #46 add issue and pr templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/tech_debt.md
  .github/pull_request_template.md
Labels: documentation

#366 #298 Rewrite to handle multiple validation docs in yaml file instead of map
  docs/oscal-validation-links.md
  src/cmd/validate/validate.go
  src/pkg/common/common.go
  src/pkg/common/types.go
  src/test/e2e/remote_validation_test.go
  src/test/e2e/scenarios/remote-validations/component-definition.yaml
  src/test/e2e/scenarios/remote-validations/multi-validations.yaml
  src/test/e2e/scenarios/remote-validations/validation.map.yaml
Labels: question

#357 feat: #298 Add the ability to pull validations from external sources (currently only backmatter)
  .github/ISSUE_TEMPLATE/bug_report.md
  docs/oscal-validation-links.md
  src/cmd/validate/validate.go
  src/pkg/common/common.go
  src/pkg/common/common_test.go
  src/pkg/common/network/network.go
  src/pkg/common/network/network_test.go
  src/pkg/common/types.go
  src/test/e2e/remote_validation_test.go
  src/test/e2e/scenarios/remote-validations/component-definition.yaml
  src/test/e2e/scenarios/remote-validations/multi-validations.yaml
  src/test/e2e/scenarios/remote-validations/pod.pass.yaml
  src/test/e2e/scenarios/remote-validations/validation.kyverno.yaml
  src/test/e2e/scenarios/remote-validations/validation.opa.yaml
  src/types/types.go
Labels: documentation, enhancement

#371 fix: remove homebrew for future updates
  .github/workflows/release.yaml
  .goreleaser.yaml
Labels: bug

#379 Fix controller runtime
  go.mod
  go.sum
  src/pkg/domains/kubernetes/resource.go
Labels: bug, dependencies
